# Generated by Django 4.2.2 on 2023-09-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_sessionprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
